---
- name: Build, Push, and Cleanup Docker Image
  hosts: localhost
  connection: local
  tasks:
    - name: Build Docker Image
      community.general.docker_image:
        name: "{{ IMAGE_NAME }}"
        tag: "{{ IMAGE_TAG }}"
        path: /path/to/dockerfile
        force: yes
      environment:
        DOCKER_PASSWORD: "{{ DOCKER_PASS }}"
      register: built_image

    - name: Push Docker Image
      community.general.docker_image:
        name: "{{ IMAGE_NAME }}"
        tag: "{{ IMAGE_TAG }}"
        push: yes
      environment:
        DOCKER_PASSWORD: "{{ DOCKER_PASS }}"
      when: built_image.changed

    - name: Push latest tag
      community.general.docker_image:
        name: "{{ IMAGE_NAME }}"
        tag: latest
        push: yes
      environment:
        DOCKER_PASSWORD: "{{ DOCKER_PASS }}"
      when: built_image.changed

    - name: Cleanup Docker Images
      shell: "docker rmi {{ IMAGE_NAME }}:{{ IMAGE_TAG }} {{ IMAGE_NAME }}:latest"
      ignore_errors: yes


