---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: build docker image using the Dockerfile
      command: docker build . -t "${ IMAGE_NAME }"

    - name: Log in to Docker Hub
      docker_login:
        username: imas10
        password: azerty12345

    - name: tag the docker image
      command: docker tag {{ IMAGE_NAME }}:latest {{ DOCKERHUB_USERNAME }}/{{ DOCKERHUB_REPOSITORY }}:latest

    - name: Push the docker image
      command: docker push {{ DOCKERHUB_USERNAME }}/{{ DOCKERHUB_REPOSITORY }}:latest


