---
- name: Build and Push Docker Image
  hosts: localhost
  tasks:
    - name: Build Docker image
      docker_image:
        name: "{{ IMAGE_NAME }}"
        tag: "{{ IMAGE_TAG }}"
        path: /Dockerfile

    - name: Push Docker image
      docker_image:
        name: "{{ IMAGE_NAME }}"
        tag: "{{ IMAGE_TAG }}"
        push: yes

    - name: Push latest Docker image
      docker_image:
        name: "{{ IMAGE_NAME }}"
        tag: latest
        push: yes
