- name: "Build Image and run container with ansible playbook"
  hosts: localhost
  tasks:
  - name: remove used image
    # Make sure to change the image name with your personal dockerhub account and reposiroty   
    command: docker rmi img-java
    ignore_errors: yes

  - name: build docker image from dockerfile
    # Make sure to change the image name with your personal dockerhub account and reposiroty 
    command: docker build -t img-java .
  
  - name: tag the docker image
    command: docker tag img-java imas10/application-java:latest
  
  - name: push image to dockerhub
    # Make sure to change the image name with your personal dockerhub account and reposiroty 
    command: docker push imas10/application-java:latest
